# Use root/example as user/password credentials

version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user_data"
      KAFKA_CREATE_TOPICS: "user_friends"
      KAFKA_CREATE_TOPICS: "user_score"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: kamehameha
      MYSQL_ROOT_PASSWORD: kamehameha
    ports:
      - '3306:3306'
    expose:
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

    